# Generated by Django 5.1.4 on 2024-12-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_created_by_recipe_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='status',
        ),
    ]
